version: '3.1'

services:
  wordpress:
    container_name: 'compro-wordpress'
    restart: always
    depends_on:
      - db
    image: 'wordpress:latest'
    ports:
      - '8080:80'
    environment:
      WORDPRESS_DB_HOST: 'db:3306'
      WORDPRESS_DB_USER: wordpress_user
      WORDPRESS_DB_PASSWORD: wordpress_password
      WORDPRESS_DB_NAME: wordpress_db
    volumes:
      - "./wordpress:/var/www/html"
  db:
    container_name: 'local-wordpress-db'
    restart: always
    image: 'mysql:8.0'
    volumes:
      - 'db:/var/lib/mysql'
      - ./docker-entrypoint-initdb.d/:/docker-entrypoint-initdb.d
    ports:
      - 18766:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wordpress_db
      MYSQL_USER: wordpress_user
      MYSQL_PASSWORD: wordpress_password
volumes:
  db: