version: '3.8'

services:
  wordpress:
    container_name: 'compro-wordpress'
    restart: always
    depends_on:
      - db_compro
    image: 'wp-compro:latest'
    ports:
      - '8080:80'
    environment:
      WORDPRESS_DB_HOST: 'db_compro:3306'
      WORDPRESS_DB_USER: wordpress_user
      WORDPRESS_DB_PASSWORD: wordpress_password
      WORDPRESS_DB_NAME: wordpress_db
    volumes:
      - "wordpress:/var/www/html"
  db_compro:
    container_name: 'wp-compro-db'
    restart: always
    image: 'mysql:8.0'
    volumes:
      - 'dbcompro:/var/lib/mysql'
      - ./docker-entrypoint-initdb.d/:/docker-entrypoint-initdb.d
    ports:
      - 6033:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wordpress_db
      MYSQL_USER: wordpress_user
      MYSQL_PASSWORD: wordpress_password
volumes:
  wordpress:
  dbcompro: